# os: linux
# language: android
# jdk: openjdk11

# android:
#  components:
#    - tools
#    - platform-tools
#    - tools
#    - extra-android-m2repository
#    - extra-android-support

# env:
#   global:
#     - TARGET_VERSION=33
#     - ANDROID_BUILD_TOOLS_VERSION=33.0.1
#     - ANDROID_HOME=~/android-sdk

# before_install:
#   - touch $HOME/.android/repositories.cfg
#   - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
#   - unzip commandlinetools.zip -d $ANDROID_HOME/
#   - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
#   - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
#   - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "system-images;android-30;default;arm64-v8a" --sdk_root=$ANDROID_HOME
#   - yes | $ANDROID_HOME/cmdline-tools/bin/avdmanager create avd --force -n test -k "system-images;android-30;default;arm64-v8a" --abi arm64-v8a
#   - emulator -avd test -no-audio -no-window &
#   - android-wait-for-emulator
#   - adb shell input keyevent 82 &

# before_script:
#  - chmod +x gradlew
# script:
#  - echo "Running UI test..."
#  - ./gradlew build connectedCheck

#---------------------------------------------------------------------------------
# language: android
# sudo: required
# jdk: oraclejdk11

# env:
#   global:
#     - ANDROID_API_LEVEL=33
#     - ANDROID_BUILD_TOOLS_VERSION=33.0.1
#     - ANDROID_ABI=armeabi-v7a

# android:
#   components:
#     - tools
#     - platform-tools
#     - extra-android-m2repository
#   licenses:
#     - 'android-sdk-preview-license-52d11cd2'
#     - 'android-sdk-license-.+'
#     - 'google-gdk-license-.+'

# before_install:
#   - touch $HOME/.android/repositories.cfg
#   - yes | sdkmanager "platforms;android-33"
#   - yes | sdkmanager "build-tools;33.0.1"
#   - sudo apt-get install libjaxb-api-java
#   - sudo apt-get install libjaxb-java

# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache:
#   directories:
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/
#     - $HOME/.android/build-cache
#     - $ANDROID_HOME

# before_script:
#   - chmod +x gradlew

# script:
#   - jdk_switcher use oraclejdk11
#   - ./gradlew clean build
#   - ./gradlew test


# language: android
# sudo: required
# jdk: oraclejdk8

# env:
#   global:
#   - ANDROID_API_LEVEL=33
#   - ANDROID_BUILD_TOOLS_VERSION=33.0.1
#   - ANDROID_ABI=armeabi-v7a

# android:
#   components:
#     - tools
#     - platform-tools
#     - tools
#     - extra-android-m2repository
#   licenses:
#     - 'android-sdk-preview-license-52d11cd2'
#     - 'android-sdk-license-.+'
#     - 'google-gdk-license-.+'

# before_install:
#   - touch $HOME/.android/repositories.cfg
#   - yes | sdkmanager "platforms;android-33"
#   - yes | sdkmanager "build-tools;33.0.1"

# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache:
#   directories:
#   - $HOME/.gradle/caches/
#   - $HOME/.gradle/wrapper/
#   - $HOME/.android/build-cache

# before_script:
#   - chmod +x gradlew

# script:
#   - jdk_switcher use oraclejdk11
#   - ./gradlew clean build
#   - ./gradlew test

# ---------------------------------------------------------------------
# language: android
# jdk: oraclejdk11

# android:
#   components:

#     - build-tools-25.0.3
#     - android-25

#     - extra-android-m2repository

#     - tools
#     - platform-tools

# before_install:
#   - mkdir "$ANDROID_HOME/licenses" || true
#   - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#   - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache:
#   directories:
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/
#     - $HOME/.android/build-cacåhe

# script:
#   - ./gradlew build


# language: android
# jdk: oraclejdk17
# # Turn off caching to avoid any caching problems
# cache: false
# sudo: true
# env:
#   global:
#     - ANDROID_API_LEVEL=33
#     - ANDROID_BUILD_TOOLS_VERSION=34.0.0
#     - ADB_INSTALL_TIMEOUT=2 # minutes (If ABD instalation pass this time, the build will throw an error)

# android:
#   components:
#     - platform-tools
#     - tools
#     - build-tools-$ANDROID_BUILD_TOOLS_VERSION
#     - android-$ANDROID_API_LEVEL
#     # Google Play Services
#     - extra-google-google_play_services
#     # Support library
#     - extra-android-support
#     # Latest artifacts in local repository
#     - extra-google-m2repository
#     - extra-android-m2repository

#   licenses:
#    - android-sdk-preview-license-.+
#    - android-sdk-license-.+
#    - google-gdk-license-.+
#    - android-sdk-license-5be876d5
# install:
#   # accept licenses for all available packages that have not already been accepted
#   - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;34.0.0"
  
# # This step is made for automatic acception of licenses whenever Travis builds the code.
# before_install:
#   - mkdir "$ANDROID_HOME/licenses" || true
#   - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#   - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#   - chmod +x gradlew
#   - ./gradlew dependencies || true

# # Run your main script
# script:
# #  - ./gradlew -PdisablePreDex
#   - ./gradlew build
  
  # --------------------------------------

# sudo: required
# language: android
# dist: trusty
# jdk:
#   - openjdk11

# android:
#   licenses:
#     - 'android-sdk-preview-license-.+'
#     - 'android-sdk-license-.+'
#     - 'google-gdk-license-.+'
 
#   components:
#     - tools
#     - build-tools-34.0.0
#     - android-33
#     - tools
#     #- android-22
#     - extra-google-google_play_services
#     - extra-google-m2repository
#     - extra-android-m2repository
#     #- sys-img-armeabi-v7a-android-22
 
# before_install:
# #   - yes | sdkmanager --update
# #   - yes | sdkmanager "platforms;android-33" "build-tools;30.0.3"
#   - chmod +x gradlew

# before_script:
#   #- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#   #- emulator -avd test -no-audio -no-window &
#   #- android-wait-for-emulator
#   #- adb shell input keyevent 82 &

# script:
#   - ./gradlew clean build
#   - ./gradlew test
#   - ./gradlew build check

# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache:
#   directories:
#   - $HOME/.gradle/caches/
#   - $HOME/.gradle/wrapper/
#   - $HOME/.android/build-cache
